import duckdb

def load_staging(con, scale):
    query = f'''

    -- Load txt and csv

    COPY staging.batchdate FROM '../../staging_area/scale_{scale}/Batch1/BatchDate.txt';
    COPY staging.cashtransaction FROM '../../staging_area/scale_{scale}/Batch1/CashTransaction.txt' delimiter '|';
    COPY staging.dailymarket FROM '../../staging_area/scale_{scale}/Batch1/DailyMarket.txt' delimiter '|';
    COPY staging.date FROM '../../staging_area/scale_{scale}/Batch1/Date.txt' delimiter '|';
    COPY staging.holdinghistory FROM '../../staging_area/scale_{scale}/Batch1/HoldingHistory.txt' delimiter '|';
    COPY staging.hr FROM '../../staging_area/scale_{scale}/Batch1/HR.csv' delimiter ',' CSV;
    COPY staging.industry FROM '../../staging_area/scale_{scale}/Batch1/Industry.txt' delimiter '|';
    COPY staging.prospect FROM '../../staging_area/scale_{scale}/Batch1/Prospect.csv' delimiter ',' CSV;
    COPY staging.statustype FROM '../../staging_area/scale_{scale}/Batch1/StatusType.txt' delimiter '|';
    COPY staging.taxrate FROM '../../staging_area/scale_{scale}/Batch1/TaxRate.txt' delimiter '|';
    COPY staging.time FROM '../../staging_area/scale_{scale}/Batch1/Time.txt' delimiter '|';
    COPY staging.tradehistory FROM '../../staging_area/scale_{scale}/Batch1/TradeHistory.txt' delimiter '|';
    COPY staging.trade FROM '../../staging_area/scale_{scale}/Batch1/Trade.txt' delimiter '|' null as '';
    COPY staging.tradetype FROM '../../staging_area/scale_{scale}/Batch1/TradeType.txt' delimiter '|';
    COPY staging.watchhistory FROM '../../staging_area/scale_{scale}/Batch1/WatchHistory.txt' delimiter '|';
    COPY staging.audit FROM '../../staging_area/scale_{scale}/Batch1_audit.csv' DELIMITER ',' HEADER CSV NULL AS '';

    -- Load FINWIRE
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1967Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1967Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1967Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1967Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1968Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1968Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1968Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1968Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1969Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1969Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1969Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1969Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1970Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1970Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1970Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1970Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1971Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1971Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1971Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1971Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1972Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1972Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1972Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1972Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1973Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1973Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1973Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1973Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1974Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1974Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1974Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1974Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1975Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1975Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1975Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1975Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1976Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1976Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1976Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1976Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1977Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1977Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1977Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1977Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1978Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1978Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1978Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1978Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1979Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1979Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1979Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1979Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1980Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1980Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1980Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1980Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1981Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1981Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1981Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1981Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1982Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1982Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1982Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1982Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1983Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1983Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1983Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1983Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1984Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1984Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1984Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1984Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1985Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1985Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1985Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1985Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1986Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1986Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1986Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1986Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1987Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1987Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1987Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1987Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1988Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1988Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1988Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1988Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1989Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1989Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1989Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1989Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1990Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1990Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1990Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1990Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1991Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1991Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1991Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1991Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1992Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1992Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1992Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1992Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1993Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1993Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1993Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1993Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1994Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1994Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1994Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1994Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1995Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1995Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1995Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1995Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1996Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1996Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1996Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1996Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1997Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1997Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1997Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1997Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1998Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1998Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1998Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1998Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1999Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1999Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1999Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE1999Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2000Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2000Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2000Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2000Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2001Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2001Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2001Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2001Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2002Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2002Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2002Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2002Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2003Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2003Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2003Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2003Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2004Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2004Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2004Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2004Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2005Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2005Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2005Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2005Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2006Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2006Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2006Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2006Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2007Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2007Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2007Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2007Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2008Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2008Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2008Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2008Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2009Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2009Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2009Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2009Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2010Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2010Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2010Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2010Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2011Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2011Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2011Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2011Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2012Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2012Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2012Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2012Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2013Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2013Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2013Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2013Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2014Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2014Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2014Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2014Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2015Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2015Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2015Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2015Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2016Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2016Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2016Q3';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2016Q4';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2017Q1';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2017Q2';
    COPY staging.finwire FROM '../../staging_area/scale_{scale}/Batch1/FINWIRE2017Q3';
    '''
    
    con.sql(query)

# test only 
scale = 3
con = duckdb.connect(f'../../database/sc_{scale}.db')
load_staging(con, scale)